### ISSUE TITLE
getPlayer().getTeam() error out when player is a spectator.

### ISSUE THREAD

**Issue by MitchDizzle** [sakki54/CSGOState#3]
I was getting an error output for when I was free roam spectating.

On a side note is there a way to check if the player is playing, and not spectating another player. When a player spectates another player it returns data for the player being spectated.

```
{"provider":{"name":"Counter-Strike: Global Offensive","appid":730,"version":13515,"steamid":"76561198007495066","timestamp":1450402525},"map":{"name":"de_cache","mode":"casual","phase":"live","round":0,"team_ct":{"score":0},"team_t":{"score":0}},"player":{"steamid":"76561198007495066","name":"MitchDizzle","activity":"textinput","state":{"health":0,"armor":0,"helmet":false,"flashed":0,"smoked":0,"burning":0,"money":1000,"round_kills":1,"round_killhs":0},"weapons":{},"match_stats":{"kills":0,"assists":0,"deaths":0,"mvps":0,"score":0}},"auth":{"token":"CCWJu64ZV3JHDT8hZc"},"round":{"phase":"live"}}
java.lang.NullPointerException
    at wtf.dizzle.csgostate.eventsounds.StatePostHandler.receivedJsonResponse(StatePostHandler.java:95)
    at com.brekcel.csgostate.post.PostReceiver.callMethods(PostReceiver.java:69)
    at com.brekcel.csgostate.post.PostReceiver.handle(PostReceiver.java:60)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
    at sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
    at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
    at sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by Brekcel** [comment]
As for the latter part use `jsr.getPlayer().getSteamid().equals(jsr.getProvider().getSteamid();` will test if the player is themself, or someone else. First part is due to Valve not sending that the player is actually a spectator, only the info about the player they're spectating. Only way I can think of getting around this is checking for a null value on getTeam() and expecting that the player is a Spectator when it's null.
